### ISSUE TITLE
Error fetching nicehash_accounts_coordinator data: 'Response' object has no attribute 'reason'

### ISSUE THREAD

**Issue by livello** [brianberg/ha-nicehash#11]
HASS core-2021.8.4

## Configuration
nicehash:
  organization_id: elishome
  api_key: ******************
  api_secret: ***************
  currency: EUR
  balances: true # (default = false) - Enable balance sensors
  rigs: true # (default = false) - Enable rig sensors
  devices: true # (default = false) - Enable device sensors
  payouts: true # (default = false) - Enable payout sensors`

## Debug log
2021-08-09 14:27:00 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry UPnP/IGD for upnp
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/upnp/__init__.py", line 90, in async_setup_entry
udn = entry.data[CONFIG_ENTRY_UDN]
KeyError: 'udn'
2021-08-09 14:27:00 ERROR (MainThread) [custom_components.nicehash.coordinators] Error fetching nicehash_accounts_coordinator data: 'Response' object has no attribute 'reason'
2021-08-09 14:27:00 ERROR (MainThread) [custom_components.nicehash] Unable to get NiceHash accounts
2021-08-09 14:27:00 ERROR (MainThread) [homeassistant.setup] Error during setup of component nicehash
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
result = await task
File "/config/custom_components/nicehash/__init__.py", line 93, in async_setup
raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady: None

**Comment by v00g100skr** [comment]
same problem with async_setup

**Comment by config-old** [comment]
Double check your cred. 
Consider check https://github.com/P1koOCod3/ha-nicehash/commit/ec4d983e445ffb30ed50d147dea8c6e12c10c53a

**Comment by Meatballs1** [comment]
should be `reason_phrase`

**Comment by spoettin** [comment]
I got this error as well when I used my freshly generated API token. I realized afterwards that Nicehash wanted me to verify the new API token ... after verification of the API token (in my case via clicking a link in an email), the error message went away and integration started working.
