### ISSUE TITLE
homeassistant.exceptions.PlatformNotReady

### ISSUE THREAD

**Issue by coreyjansen** [brianberg/ha-nicehash#2]
## Configuration

Default Yaml with my API key...
```yaml

Add your logs here.

```

## Describe the bug
Does not work at all 

## Debug log

```2021-02-05 16:23:05 ERROR (MainThread) [custom_components.nicehash.coordinators] Error fetching nicehash_mining_payouts_coordinator data: 
2021-02-05 16:23:05 DEBUG (MainThread) [custom_components.nicehash.coordinators] Finished fetching nicehash_mining_payouts_coordinator data in 8.149 seconds
2021-02-05 16:23:05 ERROR (MainThread) [custom_components.nicehash] Unable to get NiceHash mining payouts
2021-02-05 16:23:05 ERROR (MainThread) [homeassistant.setup] Error during setup of component nicehash
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/nicehash/__init__.py", line 105, in async_setup
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady

Add your logs here.

```

**Comment by brianberg** [comment]
Can you verify that `organization_id`, `api_key`, `api_secret` are correctly set in your `configuration.yaml`? I'm able to replicate this error if one of those is incorrect

**Comment by davidnite** [comment]
I had the same issue occur and it was caused by putting single quotes around the org and api secrets.

**Comment by fufar** [comment]
Hi
I have same error after restarting HA in 50% of restarts

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
    result = await task
  File "/config/custom_components/nicehash/__init__.py", line 93, in async_setup
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady: None`

`Unable to get NiceHash accounts`

`Error fetching nicehash_accounts_coordinator data:`

HA core-2021.8.6
